version: '3.7'
services:
  onijo:
    image: hanniedong117/onijo:latest
    ports:
      - 5000:5000
    environment:
      - WAIT_FOR_DB=true
      - DB_HOST=onijo-db
      - DB_PORT=5432
      - DB_HOST_TEST=onijo-test-db
      - DB_PORT_TEST=5432
      - RUN_MIGRATIONS_ON_START=true
    depends_on:
      - onijo-db
      - onijo-test-db

  onijo-db:
    image: postgres:11
    ports:
      - '5445:5432'
    environment:
      - POSTGRES_USER=onijo
      - POSTGRES_PASSWORD=onijo
      - POSTGRES_DB=onijo_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - onijopgdata:/var/lib/postgresql/data

  onijo-test-db:
    image: postgres:11
    ports:
      - 7434:5432
    environment:
      - POSTGRES_USER=onijo
      - POSTGRES_PASSWORD=onijo
      - POSTGRES_DB=onijo_test
    tmpfs:
      - /var/lib/postgresql/data

volumes:
  onijopgdata:
